x-basics: &basics
  env_file:
    - .env
  restart: unless-stopped

services:
  maria-db:
    container_name: db-maria
    image: mariadb:latest
    <<: *basics
    profiles:
      - dependencies
    networks:
      pterodactyl_nw:
        ipv4_address: 172.21.0.6
    environment:
      - MARIADB_ROOT_HOST=%
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MARIADB_DATABASE=pterodactyl
      - MARIADB_USER=pterodactyl
      - MARIADB_PASSWORD=${PTERODACTYL_PASSWORD}
    # ports:
    # - 5436:3306
    volumes:
      - ~/volumes/database/maria/data:/var/lib/mysql
      - ~/volumes/database/maria/init:/docker-entrypoint-initdb.d
      - ~/volumes/database/maria/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ../init_scripts/mariadb-init.sh:/docker-entrypoint-initdb.d/mysql-init.sh
    command:
      [
        "--log-bin=mysqld-bin",
        "--max-connections=1000",
        "--wait-timeout=28800",
        "--bind-address=0.0.0.0",
      ]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mariadb -h localhost -u root -p"${ROOT_PASSWORD}" -e "SELECT 1;"',
        ]
      start_period: 90s
      retries: 10
      timeout: 15s

  redis:
    image: "redis:latest"
    container_name: db-memory
    <<: *basics
    profiles:
      - dependencies
    command: redis-server --appendonly yes --replica-read-only no
    networks:
      pterodactyl_nw:
        ipv4_address: 172.21.0.9
    volumes:
      - "~/volumes/redis/data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  # TODO Automate `php artisan p:user:mak`
  pterodactyl:
    # image: ghcr.io/pterodactyl/panel:v1.11.7
    image: ghcr.io/pterodactyl/panel:latest
    container_name: ${PTERODACTYL_SUBDOMAIN}
    <<: *basics
    networks:
      pterodactyl_nw:
        ipv4_address: 172.21.0.4
        aliases:
          - ${PTERODACTYL_SUBDOMAIN}.${ROOT_DOMAIN}
    environment:
      - DB_HOST=maria-db
      - DB_PORT=3306
      - DB_USERNAME=pterodactyl
      - DB_PASSWORD=${PTERODACTYL_PASSWORD}
      - DB_DATABASE=pterodactyl
      - APP_URL=https://${PTERODACTYL_SUBDOMAIN}.${ROOT_DOMAIN}
      - APP_KEY=base64:ApE2v9xK5J6c0ugQ/bmY/wWbpZgMWGh2cppE53iLxvQ=
      - APP_TIMEZONE=${TZ}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=redis
      - APP_ENV=local
      - APP_ENVIRONMENT_ONLY=false
      - LOG_LEVEL=debug
      - LOG_CHANNEL=stderr
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
      - PHP_DISPLAY_ERRORS=1
      - PHP_DISPLAY_STARTUP_ERRORS=1
      - PHP_ERROR_REPORTING=E_ALL
    volumes:
      - ~/games/panel/data:/var/www/pterodactyl
      - ~/games/panel/config:/app/var
      # - ~/games/panel/logs:/app/storage/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pterodactyl.rule=Host(`${PTERODACTYL_SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.pterodactyl.entrypoints=websecure"
      - "traefik.http.routers.pterodactyl.service=pterodactyl"
      - "traefik.http.routers.pterodactyl.tls=true"
      - "traefik.http.routers.pterodactyl.tls.certresolver=sslresolver"
      - "traefik.http.services.pterodactyl.loadbalancer.server.port=80"
    depends_on:
      - maria-db
      - redis
  pterodactyl-wings:
    # image: ghcr.io/pterodactyl/wings:v1.11.13
    image: ghcr.io/pterodactyl/wings:latest
    container_name: ${PTERODACTYL_SUBDOMAIN}-daemon
    <<: *basics
    volumes:
      - ../games/config/daemon/certs:/etc/letsencrypt/live/daemon.${PTERODACTYL_SUBDOMAIN}.${ROOT_DOMAIN}
      - ../games/config/pterodactyl:/etc/pterodactyl
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
    privileged: true
    depends_on:
      - pterodactyl
    environment:
      TZ: ${TZ}
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pterodactylwings.rule=Host(`daemon.${PTERODACTYL_SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.pterodactylwings.entrypoints=websecure,pterodactyl-wings-daemon"
      - "traefik.http.routers.pterodactylwingssftp.rule=Host(`daemon.${PTERODACTYL_SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.pterodactylwingssftp.entrypoints=pterodactyl-wings-sftp"
      - "traefik.http.routers.pterodactylwings.service=pterodactylwings"
      - "traefik.http.routers.pterodactylwingssftp.service=pterodactylwingssftp"
      - "traefik.http.routers.pterodactylwings.tls=true"
      - "traefik.http.routers.pterodactylwings.tls.certresolver=sslresolver"
      - "traefik.http.services.pterodactylwings.loadbalancer.server.port=8081"
      - "traefik.http.services.pterodactylwingssftp.loadbalancer.server.port=2023"
    ports:
      - "8080:8081"
      - "2022:2023"
    networks:
      pterodactyl_nw:
        ipv4_address: 172.21.0.3
        aliases:
          - daemon.${PTERODACTYL_SUBDOMAIN}.${ROOT_DOMAIN}

networks:
  pterodactyl_nw:
    external: true
