x-basics: &basics
  env_file:
    - .env
  restart: unless-stopped

services:
  traefik:
    container_name: ${TRAEFIK_SUBDOMAIN}
    image: "traefik:latest"

    networks:
      pterodactyl_nw:
        ipv4_address: 172.21.0.5
    <<: *basics
    labels:
      # General Traefik Configuration
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=sslresolver"

    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.wss.address=:8081"
      - "--entrypoints.pterodactyl-wings-daemon.address=:8081"
      - "--entrypoints.pterodactyl-wings-sftp.address=:2023"
      - "--certificatesresolvers.sslresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.sslresolver.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.sslresolver.acme.storage=/letsencrypt/acme.json"
      # Uncomment for staging.
      - "--certificatesresolvers.sslresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "2023:2023"
    volumes:
      - ../certificates:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  pterodactyl_nw:
    name: pterodactyl_nw
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/16"
          gateway: "172.21.0.1"
