debug: true
uuid: b16bd35e-4af9-4dab-9cbb-7e8dba4b3f24
token_id: rl3u6thfszHCXce0
token: cztXcArXUmPwzK8n1gkEVET09BiQTm2k4bITwjEyz37ZXNeF9fwX1bF4AvwaPr8O
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/daemon.games.jamesonrgrieve.ca/fullchain.pem
    key: /etc/letsencrypt/live/daemon.games.jamesonrgrieve.ca/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://games.jamesonrgrieve.ca'
# docker:
#   network:
#     interface: 0.0.0.0
#     driver: bridge
#     is_internal: false
#     enable_icc: true
#     subnet: 172.21.0.0/16
#     gateway: 172.21.0.1
#     ip_range: 172.21.1.0/24
